SESSION_LIFETIME_SECONDS = 20 * 60
REFRESH_TOKEN_LIFETIME_DAYS = 7

ROLE_SUPER_ADMIN = 'super_admin'
ROLE_ADMIN = 'admin'
ROLES = (ROLE_SUPER_ADMIN, ROLE_ADMIN)

HEARTBEAT_INTERVAL_SECONDS = 30
OFFLINE_AFTER_SECONDS = 90

ENROLAMIENTO_TTL_MINUTOS = 30

ESTADOS_APP = ('permitida', 'bloqueada')
TIPOS_USO_APP = ('sin_limite', 'con_limite')

TIPOS_EQUIPO = ('pc', 'android')
